### ISSUE TITLE
needs to fix these streams

### ISSUE THREAD

**Issue by vdianl** [vdianl/plugin.audo.nlradio#3]
- [x] Stream in streams/Regionale Omroepen/Drenthe/Assen FM.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Drenthe/Radio Ideaal.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Flevoland/Almere FM.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Flevoland/Beyond The Beat Generation.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Flevoland/Urk FM.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Friesland/Smelne.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Noord Brabant/Radio Veldhoven.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Noord Brabant/Radio stad FM.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Noord Brabant/Skyline FM.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Noord Holland/Jouw FM.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Noord Holland/Radio 80.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Noord Holland/Radio Hoorn.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Noord Holland/Wild FM.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Overijssel/Accent FM.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Overijssel/Radio Almelo.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Overijssel/Radio Maico.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Overijssel/Radio Rosita.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Utrecht/Radio M Utrecht.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Zeeland/Omroep Zeeland.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Zuid Holland/Dordrechtstad FM.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Zuid Holland/Radio Hoeksche Waard.strm seems incorrect
- [x] Stream in streams/Regionale Omroepen/Zuid Holland/Studio West Ysselmonde.strm seems incorrect
- [x] Stream in streams/Seizoenen/Carnaval/Carnaval Radio.strm seems incorrect
- [x] Stream in streams/Webradio/Bright FM.strm seems incorrect
- [x] Stream in streams/Webradio/Radio 251.strm seems incorrect
- [x] Stream in streams/Webradio/Seven FM.strm seems incorrect
- [x] Stream in streams/Juize FM.strm seems incorrect
- [x] Stream in streams/Sublime FM.strm seems incorrect

---
- [x] = Checked and fixed
- [ ] = Still open

**Comment by pvdl** [comment]
Use '- [' and ']' in your mark up. You can easily 'check' them when completed.
- [x] Stream xx seems incorrect
- [ ] Stream zz seems incorrect

Info : https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments

**Comment by vdianl** [comment]
These streams do work, despite of the error of the testing script
streams/Regionale Omroepen/Noord Brabant/Skyline FM.strm
